docs/condition.csv
src/extractors/CSVConditionExtractor.js
src/extractors/index.js
src/helpers/ejsUtils.js
src/templates/Condition.ejs
test/extractors/CSVConditionExtractor.test.js
test/extractors/fixtures/csv-condition-bundle.json
test/extractors/fixtures/csv-condition-module-response.json
test/templates/condition.test.js
test/templates/fixtures/condition-resource.json

Added CSV format for condition information and extractor to retrieve data.
New CSV extractor to extract condition data
- Added EJS template and test for Condition resource
- `category` and `verificationStatus` were required fields. I gave them values of `encountered-diagnosis` and `confirmed` in the template. Did we want different values here? Did we want to include this in the CSV format?
- Added `CSVConditionExtractor`
- Review CSV format
- I put `codeSystem` and `code` as separate values for easier parsing. Did we want to combine these into one value that we would parse (e.g. value would be `system: code`)?
- Did we want to only allow codes from one system in which case we would only have a `code` value in the csv format?
- Ensure tests pass

Condition CSV Extractor

---

test/extractors/CSVClinicalTrialInformationExtractor.test.js

Added one one last check in the ClinicalTrialExtractor test to ensure data gets formatted properly (it's pretty simple in the CSV case).

Check formatted data

---

src/extractors/BaseFHIRExtractor.js
src/extractors/CSVClinicalTrialInformationExtractor.js
src/helpers/conditionUtils.js
src/helpers/ejsUtils.js
src/helpers/fhirUtils.js
src/index.js
test/extractors/BaseFHIRExtractor.test.js
test/extractors/CSVClinicalTrialInformationExtractor.test.js

Extractors now parse context bundle for resources
- Added helper function in `fhirUtils` to use `fhirpath` to search for resources in bundle
- Added logic to parse context bundle in `BaseFHIRExtractor` and `CSVClinicalTrialInformationExtractor`
- Added tests to make sure resources are being retrieved from context instead of from fhir module.
- Ensure tests pass
- Ensure quality of the code
- Run the CSV Client
- Make sure to update the `package.json` to point to the `context-aware` branch.
- In the log statements when the `CSVClinicalTrialInformationExtractor` is running, it should log that patient resource is found in context.
- The resulting bundle generated by the client should use the patient id for the research subject instead of the mrn.

Context Aware Extractors

---

src/templates/CancerDiseaseStatus.ejs
src/templates/CarePlanWithReview.ejs
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-treatment-plan-change-bundle.json
test/templates/fixtures/careplan-resource.json
test/templates/fixtures/disease-status-resource.json

Straightforward - updated profiles to reference correct URL's. Bundles created using these resources should now validate on the `icare-ext-client` repo. 
Testing: 
- Verify manually that these are the canonical URL's listed on both IG's, found here:
- http://standardhealthrecord.org/guides/icare/StructureDefinition-icare-care-plan-with-review.html 
- http://hl7.org/fhir/us/mcode/StructureDefinition-mcode-cancer-disease-status.html

Updated profiles

---

docs/cancer-disease-status.csv
docs/patient.csv
docs/treatment-plan-change.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/extractors/CSVPatientExtractor.js
src/extractors/CSVTreatmentPlanChangeExtractor.js
test/extractors/CSVCancerDiseaseStatusExtractor.test.js
test/extractors/CSVTreatmentPlanChangeExtractor.test.js
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-cancer-disease-status-module-response.json
test/extractors/fixtures/csv-patient-bundle.json
test/extractors/fixtures/csv-patient-module-response.json
test/extractors/fixtures/csv-treatment-plan-change-bundle.json
test/extractors/fixtures/csv-treatment-plan-change-module-response.json

This PR implements changes to remove the `subjectId` column from the TreatmentPlanChange and CancerDiseaseStatus extractors, and remove the `patientId` column from the Patient extractor. No changes are made to other extractors.
The new changes cause the subject ID field for each relevant template to use the MRN instead of the subject's ID itself. No other apparent changes should be noticeable.
The `.csv` files for TreatmentPlanChange, CancerDiseaseStatus, and Patient have their `subjectID` and `patientID` columns removed. The related extractors have the requirement for the `subjectID` and `patientID` columns removed, and use the `mrn` field wherever the removed fields were previously used. All test files requiring changes have been updated accordingly.
Run the `icare-extraction-client` …

Remove subject ID from CSV extractors, use MRN instead

---

src/templates/CancerDiseaseStatus.ejs
src/templates/CarePlanWithReview.ejs
src/templates/Condition.ejs
src/templates/ResearchSubject.ejs
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-clinical-trial-information-bundle.json
test/extractors/fixtures/csv-condition-bundle.json
test/extractors/fixtures/csv-treatment-plan-change-bundle.json
test/templates/fixtures/careplan-resource.json
test/templates/fixtures/condition-resource.json
test/templates/fixtures/disease-status-resource.json
test/templates/fixtures/research-subject-resource.json

Changed templates to use generic reference ids
- Updated templates and test fixtures to use `urn:uuid` as prefix for reference ids instead of `Patient/` or `Condition/`.
Ensure tests are good and other repos work fine with these changes.

Changed templates to use generic reference ids

---

src/extractors/CSVClinicalTrialInformationExtractor.js
src/templates/ResearchStudy.ejs
test/extractors/CSVClinicalTrialInformationExtractor.test.js
test/extractors/fixtures/csv-clinical-trial-information-bundle.json
test/templates/condition.test.js
test/templates/fixtures/research-study-resource.json
test/templates/researchStudy.test.js

Update the CSVClinicalTrialInformationExtractor to accept a ClinicalSiteId as a constructor argument, and update the templates to use that constructor argument.
See above
Updates to tests (also added describes where appropriate); changes to class to support new features. 
- Ensure these local tests pass;
- Ensure that the local `mcode-extraction-framework/test/templates/fixtures/research-study-resource.json` validates against R4;
- Looking at the #site-id PR on ICARE-ext-client, ensure that things fail and messages are logged appropriately when information is missing from the configuration file; 
- When the configuration file is updated to provide the ClinicalSiteId as a constructor arg for ClinicalTrialInformationExtractors, ensure that running the client doesn't fail for that. …

ClinicalTrialInformation Extractor uses ClinicalSiteId

---

docs/cancer-disease-status.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/helpers/diseaseStatusUtils.js
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-cancer-disease-status-module-response.json

Update CSV format for CDS (not clinical-decision-support) to use codes instead of display text for CDS response values.
None
- Update example fixtures to use new format
- New CDS util for mapping codes to display text
- Update CSVCDSExtractor to assume `record.diseaseStatus` is a code not a display string
- Ensure tests pass
_only needs one reviewer_

Update tests and code to us codes in lieu of text

---

docs/cancer-disease-status.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/helpers/diseaseStatusUtils.js
src/helpers/ejsUtils.js
src/templates/CancerDiseaseStatus.ejs
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-cancer-disease-status-module-response.json
test/helpers/diseaseStatusUtils.test.js
test/templates/cancerDiseaseStatus.test.js
test/templates/fixtures/disease-status-resource.json

Adds evidence as a new required parameter of the CDS template and augments the CSV-CDS extractor to parse the evidence appropriately  
CSV files containing CDS data must now have an evidence column, and a value that contains a pipe-delimited list of codes associated with evidences coming from the following value set: http://hl7.org/fhir/us/mcode/ValueSet-mcode-cancer-disease-status-evidence-type-vs.html
Update tests to supply this newly required piece of data; augment the EJS template to handle the iteration over a list of evidences and add them to the rendered template accordingly; adding a evidence-type code lookup akin to the disease-status code lookup
Ensure test pass, linting passes, and that the ICARE-extraction-client's sibling branch works as expected. 
Probably want two sets of …

Cds evidence csv

---

docs/cancer-disease-status.csv
docs/treatment-plan-change.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/extractors/CSVTreatmentPlanChangeExtractor.js
src/helpers/fhirUtils.js
src/index.js
src/modules/CSVModule.js
test/extractors/CSVCancerDiseaseStatusExtractor.test.js
test/extractors/CSVClinicalTrialInformationExtractor.test.js
test/extractors/CSVTreatmentPlanChangeExtractor.test.js
test/modules/CSVModule.test.js
test/modules/fixtures/csv-response.json
test/modules/fixtures/example-csv.csv

Adds support for filtering out CSV data based on a provided `fromDate` and `toDate`.
You can now run the client with a `--fromDate` and `--toDate` specified for CSV extraction. The fromDate (or one from the log file if not provided) and the toDate (if provided) are then used to filter out data in the CSV module `get`. If all data is filtered out, we return an empty collection bundle.
Added filtering to CSV Module `get` based on a `fromDate` and `toDate`, if provided and valid dates. Return an empty bundle if no patient information is returned from extractor's `get`. Added tests for both of those changes. I also updated the joinAndReformat test in the CancerDiseaseStatus tests to more closely mirror the ones in TreatmentPlanChange and ClinicalTrialInfo since it was functionally the same, …

Support filtering by fromDate and toDate in CSV module

---

src/extractors/CSVTreatmentPlanChangeExtractor.js
test/extractors/CSVTreatmentPlanChangeExtractor.test.js
test/templates/carePlanWithReview.test.js

Small change to check for `reasonCode` only when `changed` is `'true'`
Ensure tests pass and changes make sense
Run with client to ensure everything still works
One reviewer on this should be fine.

Require `reasonCode` only when `changed` is true

---

README.md
src/extractors/BaseFHIRExtractor.js
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/extractors/CSVClinicalTrialInformationExtractor.js
src/extractors/CSVConditionExtractor.js
src/extractors/CSVPatientExtractor.js
src/extractors/CSVTreatmentPlanChangeExtractor.js
src/helpers/ejsUtils.js
src/modules/BaseFHIRModule.js
src/modules/CSVModule.js

Updates all `logger.info` statements to be `logger.debug` statements. 
No new code behavior, but limits the number of statements that get logged when running the CLI using extractors in this repo.
Uses `logger.debug` instead of `logger.info`. I also tried to align the logging statements across extractors, so I added a few debug statements in extractors to match those in the other extractors.
One small side effect is that the `log.warn` statements stand out a little more, but I think they all seem valid as warnings, so I left them.
Using the `icare-extraction-client` branch, running the CSV Client should result in fewer log statements and make the output easier to understand but still give a summary of what is happening.
I also have screenshots of the old logs and the new logs, so if …

Update to debug statements

---

docs/patient.csv
src/extractors/CSVPatientExtractor.js
src/helpers/diseaseStatusUtils.js
src/helpers/helperUtils.js
src/helpers/patientUtils.js
src/index.js
src/templates/Patient.ejs
test/extractors/CSVPatientExtractor.test.js
test/extractors/fixtures/csv-patient-bundle.json
test/extractors/fixtures/csv-patient-module-response.json
test/extractors/fixtures/patient-bundle.json
test/helpers/patientUtils.test.js
test/templates/fixtures/maximal-patient-resource.json
test/templates/fixtures/patient-resource.json
test/templates/patient.test.js

Expand the Patient CSV Extractor to support new fields, including: 
- dateOfBirth,
- race,
- ethnicity,
- language,
- address,
- city,
- state,
- zip
CSV's can have those values and they will be exported into FHIR templates, but templates will still render if some of that data is missing.
- Updated the docs file for patient CSV format
- Added new utils in `patientUtils` for translating ethnicity and race codes
- Updated the `Patient.ejs` template to support these new optional fields
- Updated the CSVPatientExtractor to support these new fields, adding explicit requirement of some fields based on the Spec document provided by Rob in #shr-steam 
- Updated comments to be accurate in `diseaseStatusUtils`
- Created new tests and updated tests where needed
- Ensure all tests pass
- Try …

Expand Patient CSV to handle more values

---

src/client/BaseClient.js
src/index.js
test/client/BaseClient.test.js

Added `BaseClient` to this repo so that it can be used by extraction clients that import this repo.
Newly created [base-icare-extraction-client](https://github.com/mcode/base-icare-extraction-client) extends this class.

Added BaseClient

---

src/client/BaseClient.js
test/client/BaseClient.test.js

Updated `BaseClient` to return errors encountered during extraction along with context bundle.
Additional return value in `get` function of `BaseClient`
Test PR in `base-icare-extraction-client` and ensure errors aggregated.

Aggregate extraction errors

---

docs/cancer-disease-status.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/helpers/diseaseStatusUtils.js
src/helpers/ejsUtils.js
src/templates/CancerDiseaseStatus.ejs
test/extractors/CSVCancerDiseaseStatusExtractor.test.js
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-cancer-disease-status-module-response.json
test/helpers/diseaseStatusUtils.test.js
test/templates/cancerDiseaseStatus.test.js
test/templates/fixtures/minimal-disease-status-resource.json

Added support for an additional `observationStatus` field in the CancerDiseaseStatus extractor.
The extractor can now extract attributes for `observationStatus` and `diseaseStatusText`. It will no longer be able to extract a value for `dateRecorded`, per the example csv file. 
1. Added new example fields in `docs/cancer-disease-status.csv`.
2. Updated the Cancer Disease Status extractor to throw an error if `observationStatus` is omitted given that it is a mandatory attribute. Also updated the extractor to read in a display value for `diseaseStatus`, falling back to a lookup with the `diseaseStatus` code by way of the helper functions in `src/helpers/diseaseStatusUtils.js` if a display value is not included.
3. Updated the diseaseStatusText values in `src/helpers/diseaseStatusUtils.js`. …

New fields added to cancer disease status

---

docs/cancer-disease-status.csv

I realized that the `dateRecorded` column was removed from the CancerDiseaseStatus CSV sheet. We had added this column to reflect the date the entry was added to the CSV sheet and use it to filter out data during extraction. However, since this doesn't map onto an element in the FHIR resource, it isn't reflected in Rob's spreadsheet. I can update the spreadsheet as well, as long as everyone agrees we should still have this column.

Add dateRecorded column to Cancer Disease Status

---

docs/cancer-disease-status.csv
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/templates/ResearchSubject.ejs
test/extractors/CSVCancerDiseaseStatusExtractor.test.js
test/extractors/fixtures/csv-clinical-trial-information-bundle.json

While I was reviewing the ICARE documentation, I noticed a couple things that the extraction framework needed to update.
- We added in an `observationStatus` field in the cancer disease status CSV, but this should be an optional field in the CSV file. Even though it is a required `1..1` property in FHIR, we can reasonably assume a default value of `final` since this is describing the status of the FHIR resource and not anything to do with an observed piece of patient data (also confirmed this with Rob and others at stand up last week). This PR makes the `observationStatus` field no longer a required field and defaults it to 'final' if it is not provided.
- The way we were referencing the ResearchStudy on the ResearchSubject was incorrect. Most of our references to other resources within …

Minor updates for ObservationStatus and Study Reference

---

src/helpers/conditionUtils.js
src/templates/ConditionTemplate.js
test/extractors/fixtures/csv-condition-bundle.json
test/extractors/fixtures/csv-condition-module-response.json
test/helpers/conditionUtils.test.js
test/templates/condition.test.js
test/templates/fixtures/cancer-condition-resource.json
test/templates/fixtures/maximal-condition-resource.json
test/templates/fixtures/minimal-condition-resource.json

Only cancer conditions should include the "disease" category coding.
Previously, we were adding the "disease" category coding to all conditions. This value is only fixed on primary and secondary cancer conditions, so it should only be included in the `category` array on those conditions. Now that we have the flexibility in our templates to support this, we are implementing this change.
Use the util functions to determine if a condition is a cancer condition. Only apply the "disease" fixed value on category if it is a cancer condition.
I also reformatted a couple JSON files, which should be contained to b3f8b7b. The changes for the task should be contained to 322e0f1 if it is easier to see the diffs.
Run the test and ensure they pass. Ensure the changes to the tests make sense. I did …

Category on cancer conditions

---

src/templates/CancerRelatedMedicationTemplate.js
test/templates/fixtures/minimal-medication-resource.json

Properly handles the omission of the `startDate` and `endDate` fields from a csv. Prior to this, the resource would be generated but the message would fail to send.
`startDate` and `endDate` being omitted from the csv now results in the corresponding fields being left out of the effectivePeriod element, rather than nulling out their respective properties. 
1. Added two conditionals to the `periodTemplate` function within the CancerRelatedMedication template. These conditionals omit either `start` or `end` from the `period` property if they are not included in the csv.
2. Updated the minimal cancer related medication json to reflect the new behavior.
When running from the base icare client, remove the startDate and endDate columns within `cancer-related-medication-information.csv` and …

Period hotfix

---

docs/config.example.json
docs/patient-mrns.csv

One of 3-4 PR's for updating README's. Changes here include: 
- Adding documentation for how patient-mrns are supposed to be specified;
- Moving our example configuration file (more of a developer/documentation piece of information) from the base-client to here. This will make even more sense when we complete task [STEAM-379](https://jira.mitre.org/browse/STEAM-379) and move some of the CLI utils from the base-client to the base-MEF.
Should only need one PR reviewer. And should be reviewed while reviewing it's sibling PR on the base-client repo, to ensure that all the necessary information from that repo is moved over here.

Readme update

---

src/templates/CancerDiseaseStatusTemplate.js
src/templates/CancerRelatedMedicationTemplate.js
src/templates/CarePlanWithReviewTemplate.js
src/templates/ConditionTemplate.js
src/templates/ObservationTemplate.js
src/templates/ProcedureTemplate.js
src/templates/snippets/bodySiteTemplate.js
src/templates/snippets/index.js
src/templates/snippets/valueX.js
test/templates/snippets/valueX.test.js

An optional `type` parameter has been added to the `valueX()` snippet. The `valueCodeableConcept()` snippet has also been removed and integrated with the `valueX` snippet.
The `valueX()` function will now default to using the `type` parameter to determine the return type when this parameter is included. If the type parameter is not included; or is included and the specified type is not recognized, the old inferential approach is used. Also, the separate `valueCodeableConcept` snippet has been removed in favor of including `'valueCodeableConcept'` as a parameter in the base `valueX` snippet.
1. `type` was added as an optional parameter to the `valueX()` snippet. A `valueByType()` helper function has also been introduced, returning the appropriate value[x] element based on the type …

ValueX type parameter

---

src/extractors/BaseFHIRExtractor.js
src/helpers/fhirUtils.js
src/index.js
src/modules/BaseFHIRModule.js
test/modules/BaseFHIRModule.test.js
test/modules/fixtures/operation-outcome-bundle.json

When an `OperationOutcome` is present, we now log more detailed information from that resource.
Right now, I think the only time we could get an `OperationOutcome` is from a `search` from the BaseFHIRModule. When we get the bundle back from the search, we should look to see if there is an [OperationOutcome](https://www.hl7.org/fhir/operationoutcome.html) resource on it. If there is, we log the information on that resource. Severity and code are required on the resource, so I assume those are always present. If other information is present, it is added. I thought the list of codes was a lot of information in the log statements, so I put that list in a `debug` so it is only logged if we use `--debug`.
Added a helper function to do the logging for OperationOutcome information.
Test to make …

Improve logging when OperationOutcomes are present

---

src/templates/CancerRelatedMedicationTemplate.js
src/templates/snippets/extension.js
src/templates/snippets/index.js
test/templates/fixtures/minimal-medication-resource.json
test/templates/medication.test.js

If both start and end date are not provided in the related medication CSV, the data absent reason extension is used in the `effectivePeriod` element.
The extension will be used in the `effectivePeriod` element if there is no start and no end date provided in the CSV. I decided to use "unknown" as the reason code because the description said "The value is expected to exist but is not known." which I thought was most applicable to the situation where we are missing dates.
I made the extension a snippet since I figured there may be other places we'd want to use it in the future. You can provide the specific reason code when using the snippet.
I tested using the VS Code FHIR Validator extension, but ensure that the output now validates (at least around the MedicationStatement …

Data Absent Reason extension

---

test/helpers/fhirUtils.test.js
test/helpers/fixtures/count-bundle-5-nested.json
test/helpers/fixtures/count-bundle-5-same.json
test/helpers/fixtures/count-bundle-5-unique.json

Tests the `getResourceCountInBundle` function now. Also reorganized the tests in`fhirUtils.test.js` to better use describe blocks where appropriate. 
Not a whole lot happening here, so this should be good to merge with one approval.

Added tests for getResourceCountInBundle

---

src/extractors/MCODESurgicalProcedureExtractor.js
src/extractors/index.js
src/helpers/valueSets/ValueSet-mcode-cancer-related-surgical-procedure-vs.json
src/index.js
test/extractors/MCODESurgicalProcedureExtractor.test.js
test/extractors/fixtures/surgical-procedure-bundle.json

This PR adds a new extractor for mCODE Cancer Related Surgical Procedures.
The approach I took for this extractor is similar to the Epic Conditions extractor. It will get all Procedure resources using the regular FHIR Procedure extractor and then will filter that list to only include ones that have a code in the mCODE VS for Cancer Related Surgical Procedures.
Adds the new extractor and adds tests for the new extractor.
Since this extractor uses the FHIR services to get procedures, you'll need to test it using the epic-MEF repo. There is a PR there to help set up your config and instructions to test it out.
Note: we have another task for extracting radiation procedures. If we continue working on that task next week while I'm out, I'm fine if this PR gets closed or changed in any way. …

WIP: mCODE Surgical Procedure Extractor

---

src/extractors/MCODERadiationProcedureExtractor.js
src/extractors/MCODESurgicalProcedureExtractor.js

Removes a number of commented out blocks of code that leveraged the previous context strategy. Until we decide how Context ought to be used, I'm removing that commented out code.

Removes commented out blocks of code

---

src/client/BaseClient.js

Added try catch block for better error management in the case of extractor initialization. 
Test that the error is helpful by 1) changing the type of an extractor in your config file to be nonsense, and 2) reviewing the error message for quality. 
Also test that normal extraction works as expected. 
**_only needs one reviewer_**

Improve error message on unsuccessful extractor initialization 

---

src/extractors/CSVTreatmentPlanChangeExtractor.js
src/templates/CarePlanWithReviewTemplate.js
test/extractors/CSVTreatmentPlanChangeExtractor.test.js
test/extractors/fixtures/csv-treatment-plan-change-bundle.json
test/extractors/fixtures/csv-treatment-plan-change-module-response.json
test/templates/carePlanWithReview.test.js
test/templates/fixtures/maximal-careplan-resource.json
test/templates/fixtures/minimal-careplan-resource.json

He's back baby.
Updates Care plan extractor/template to create multiple extension entries rather than multiple CarePlan resources when provided >1 entry to the extractor.
Multiple CarePlan data entries now appear as multiple `http://mcodeinitiative.org/codex/us/icare/StructureDefinition/icare-care-plan-review` extensions in the outputted CarePlan resource
* Update joinAndReformat function to produce a new type of data (each "review" maps to a new extension)
``` Javascript
{
mrn: 'mrn-1',
reviews: [
{
effectiveDate: '2020-04-15',
hasChanged: 'true',
reasonCode: '281647001',
},
...
],
}
```
* Update tests/fixtures accordingly
* Removed the usage of the `created` property for now as it is not required and we want to avoid inferring its value based on the multiple dates that could now be …

Update careplan to create multiple extensions

---

src/helpers/contextUtils.js
src/index.js
test/helpers/contextUtils.test.js

After realizing how many extractors will depend on getting the patient from context, this PR moves the utility from the E-MEF to this repo.  
Minimal, as this PR doesn't concern itself with using the functionality anywhere in this repo. 
- Adds this utility;
- Adds tests for the utility;
- Exports the utility.
- Make sure tests pass, especially the new ones. 
- Connect this with the E-MEF repo and ensure that tests pass there too.

Added context utilities to the base-MEF

---

src/client/BaseClient.js
src/extractors/BaseFHIRExtractor.js
src/extractors/MCODERadiationProcedureExtractor.js
src/extractors/MCODESurgicalProcedureExtractor.js
test/extractors/BaseFHIRExtractor.test.js
test/extractors/FHIRAdverseEventExtractor.test.js
test/extractors/FHIRAllergyIntoleranceExtractor.test.js
test/extractors/FHIRConditionExtractor.test.js
test/extractors/FHIRMedicationRequestExtractor.test.js
test/extractors/FHIRObservationExtractor.test.js
test/extractors/MCODERadiationProcedureExtractor.test.js
test/extractors/MCODESurgicalProcedureExtractor.test.js
test/extractors/fixtures/patient-bundle.json

This PR updates the `BaseFHIRExtractor` to require the `Patient` resource to be in context when it is used to search for other resource types.
When any of the generic FHIR resource extractors are run before the `FHIRPatientExtractor`, an error will be thrown and that resource will not be extracted. When the `FHIRPatientExtractor` is run first, the behavior is unchanged.
Removed the `BaseFHIRModule` search for `Patient` when the `Patient` resource was not on the context bundle. Instead, throw an error.
Added a test in `BaseFHIRExtractor` to test for this new error. Also updated the other FHIR extractors that now needed a `Patient` on context. I did not add a test on each of the FHIR extractors to show that an error would be thrown if `Patient` was missing from context because I felt that …

Updated Context Management in BaseFHIRExtractor

---

src/helpers/fhirUtils.js
src/index.js
src/templates/ResearchSubjectTemplate.js
test/helpers/fhirUtils.test.js

The motivation for this was to include the system of the ResearchStudy identifier that now gets searched for in the Epic extractor. We were always defaulting this to an example.com system. Now that we will sometimes have the system from the actual resource we search for, we want to pass this through.
If using Epic extractor and find a ResearchStudy resource via an API call, the system will persist over to the `study` attribute of the corresponding  `ResearchSubject` resource that is generated using the template
* ResearchSubject template now includes a defaulted arg for the identifier system of the ResearchStudy.
* Add fn in fhirUtils that grabs first identifier (null if not present), and corresponding unit tests
Ensure current behavior in base MEF is unchanged. More thorough testing can …

Add identifier helper and update ResearchSubject template

---

src/helpers/contextUtils.js
src/index.js
test/helpers/contextUtils.test.js

This PR adds a util function for getting Condition resources from context.
Adds a new util function, but no new behavior since it is not yet used in this repo.
- Removes the MRN parameter from both ConditionContextUtils; it's late and I'd be happy to talk about reverting this tomorrow, but it felt right to avoid this habit of stubbing out variables we might get around to using in the future. Rob was right, as usual. 
- Add the function and tests for the function
- Added JS Docs for both condition functions in `contextUtils.js`
- Minor variable name changes in getConditionEntriesFromContext.
Check that the tests are sufficient for the function. The use of this function will really be tested in the related PR in the Epic-MEF (there are instructions in that PR).

Creates a getConditionsFromContext function for parsing Condition resources off Context

---

src/extractors/BaseFHIRExtractor.js
src/extractors/FHIRAdverseEventExtractor.js
src/extractors/FHIRAllergyIntoleranceExtractor.js
src/extractors/FHIRConditionExtractor.js
src/extractors/FHIRMedicationRequestExtractor.js
src/extractors/FHIRObservationExtractor.js
src/helpers/contextUtils.js
test/extractors/BaseFHIRExtractor.test.js
test/extractors/FHIRAdverseEventExtractor.test.js
test/extractors/FHIRAllergyIntoleranceExtractor.test.js
test/extractors/FHIRConditionExtractor.test.js
test/extractors/FHIRMedicationRequestExtractor.test.js
test/extractors/FHIRObservationExtractor.test.js
test/helpers/contextUtils.test.js

**NOTE: I've made the base-branch the current staging-context PR for the sake of readability; this needs to change before merging**
PR should remove any references to the MRN in calls to the `parametrizeArgsForFHIRModule` function. 
Testing should CTRL+F around for any missed instances of vestigial MRN's, and testing should ensure that (you guessed it) tests pass.

Removing the use of MRN in the parametrize function

---

src/extractors/CSVCancerDiseaseStatusExtractor.js
src/templates/CancerDiseaseStatusTemplate.js
test/extractors/CSVCancerDiseaseStatusExtractor.test.js
test/templates/cancerDiseaseStatus.test.js
test/templates/fixtures/minimal-disease-status-resource.json

The CancerDiseaseStatusExtractor now excludes a `valueCodeableConcept` value from the resulting resource when a value corresponding to `not evaluated` is included in the diseaseStatusCode field.
When `709137006` (the code corresponding to `not evaluated`) is included in the diseaseStatusCode column of a CDS csv file, the CancerDiseaseStatusExtractor now populates the valueCodeableConcept element with a `dataAbsentReason` extension with a value of `not-asked`.
1. If the `value` object that is passed into the CancerDiseaseStatusTemplate from the extractor includes a `code` value of `709137006`, the template generates the `valueCodeableConcept` property with a `dataAbsentReason` extension.
2. The minimal extraction test case within the CancerDiseaseStatus template test file has been updated …

Parsing of 'not evaluated' status value in CDS extractor

---

src/helpers/diseaseStatusUtils.js
src/helpers/lookups/diseaseStatusLookup.js
src/templates/CancerDiseaseStatusTemplate.js
test/helpers/diseaseStatusUtils.test.js
test/sample-client-data/cancer-disease-status-information.csv
test/templates/cancerDiseaseStatus.test.js
test/templates/fixtures/minimal-disease-status-resource.json

Pretty straightforward. This work fixes a previous oversight in our CDS lookup object, fixing one of our k-v pairs and adding a new one for `not evaluated: not-asked`. I had to make minor adjustments to our CDS-dataAbsentReason logic, so that our Template managed these new. codes appropriately. I've also added a new test to check for dataAbsentReason specific properties.
Addl changes: 
- Changed a few comments in `diseaseStatusUtils.js`, but those are tangentially related to the main task. 
Note: Also looks like more changes were made to `minimal-disease-status-resource.json` then actually were because of linting disparities. C'est la vie. 
**One Assignee should be sufficient**

Fixes the CDS lookup to distinguish between `undetermined` and `not evaluated`

---

src/extractors/CSVClinicalTrialInformationExtractor.js
src/templates/ResearchStudyTemplate.js
src/templates/ResearchSubjectTemplate.js
test/extractors/CSVClinicalTrialInformationExtractor.test.js
test/extractors/fixtures/csv-clinical-trial-information-bundle.json
test/extractors/fixtures/csv-clinical-trial-information-module-response.json
test/sample-client-data/clinical-trial-information.csv
test/templates/fixtures/research-study-resource.json
test/templates/researchStudy.test.js

ClinicalTrialInformationExtractor can now take an optional column for trialResearchSystem
ClinicalTrialInformationExtractor can now take an extra column for trialResearchSystem in it's CSV input. If the column is omitted from the CSV, the "system" field in the resulting study resource will also be omitted. The value can also be blank in any individual row of the CSV and the "system" field in the study resource will also be omitted
1. Changed CSVClinicalTrialInformationExtractor.js to take the new field, defaulting to no value if it isn't provided. Since the field is optional, it won't throw an error if it is missing
2. Changed ResearchStudyTemplate.js and ResearchSubjectTemplate.js to take in trialReseachSystem as a parameter, previously they just had hard coded default values
3. Changed …

Added optional trialResearchSystem column to ClinicalTrialInformationExtractor

---

src/templates/CarePlanWithReviewTemplate.js
test/templates/carePlanWithReview.test.js

The conditional which throws an error if the `hasChanged` element is missing from a review now checks for a `null` value rather than an `undefined` value. 
No new behavior.
1. The conditional within the `carePlanChangeReasonExtensionTemplate` has been updated to check for a `null` value.
2. The missing data test within the carePlanWithReview template test file has been updated to check for the relevant `hasChanged` error explicitly, rather than checking that an error was thrown generally.
Ensure that the change to the care plan template tests make sense, as no new behavior should be introduced in this PR.

Fixed hasChanged check within carePlanChangeReasonExtensionTemplate

---

src/extractors/CSVPatientExtractor.js
src/extractors/FHIRPatientExtractor.js
src/helpers/patientUtils.js
test/helpers/fixtures/masked-patient-bundle.json
test/helpers/patientUtils.test.js

A set number of fields can now be specified to be masked with dataAbsentReason extensions in a Patient resource
The CSV Patient Extractor and FHIR Patient Extractor can now take an optional constructor argument "mask", which is an array containing any number of fields that are capable of being masked. The specified fields will have their values replaced by dataAbsentReason extensions with the code 'masked'. The fields that can currently be masked are any values the CSV Patient Extractor can take as input (currently "gender", "mrn", "name", "address", "birthDate", "language", "ethnicity", "birthsex" and "race")
- `patientUtils.js` now has a function called `maskPatientData` that takes a FHIR bundle with a Patient resource and an array of fields to mask. maskPatientData will modify the …

Adding ability to mask fields in Patient resource

---

README.md
config/csv.config.example.json
src/cli/emailNotifications.js
test/cli/emailNotifications.test.js

This supports setting TLS rejectUnauthorized through configuration.
For some reason unknown to me, it doesn't appear that `nodemailer` is using `NODE_EXTRA_CA_CERTS` properly, so if you are using that but don't have `NODE_TLS_REJECT_UNAUTHORIZED="0"` set, `nodemailer` would throw an error saying `unable to verify the first certificate`. I couldn't figure out how to get the `NODE_EXTRA_CA_CERTS` to work properly with `nodemailer`, so instead this PR supports setting `tls.rejectUnauthorized` from through a configuration field `tlsRejectUnauthorized` (I thought the flatter configuration structure was simpler). This is an optional configuration property. If it is left off, `tls.rejectUnauthorized` defaults to `true` when setting up the nodemailer transport, which is the behavior we would want …

Support TLS Reject Unauthorized in config

---

src/extractors/CSVClinicalTrialInformationExtractor.js

trialResearchSystem will no longer default to an "example.com" value when not provided in the CSV
When no trialResearchSystem is provided in the CSV, the 'system' field will be omitted instead of given a default value
CSVClinicalTrialInformationExtractor.js no longer assigns an 'example.com' default value to trialResearchSystem
- Make sure that when no trialResearchSystem is provided, the resulting ResearchStudy has an identifier with no 'system' field
- Make sure the extractor still works as expected otherwise and tests still pass

Removed default value for trialResearchSystem in ClinicalTrialInformationExtractor

---

README.md
src/cli/app.js

If a log file does not exist and no custom log file is specified, a new file is created at the default location.
When running the program with the `--entries-filter` flag, if no log file exists at `logs/run-logs.json`, then the file is created and initialized with an empty array. This won't happen if a custom log file is specified.
- `checkLogFile` function in `app.js` now creates a default log file if one doesn't exist.
- `README.md` has been updated to better reflect the logging functionality
- Test that a log file is created when there is no file at `logs/run-logs.json`
- Example command to run: `node src/cli/cli.js -e -f 2019-01-01 -t 2021-01-01`
- Test that specifying a custom log file still works as it should
- Make sure the changes to the README accurately reflect how logging works

Create default log file if one does not exist

---

src/cli/app.js
src/helpers/patientUtils.js
test/helpers/fixtures/bundle-with-mrn-id.json
test/helpers/patientUtils.test.js

Since the MRN is used as an ID on the patient resource, it appears as a reference in other resources. Now when masking the MRN, all of those references will also be masked by replacing the MRN with a hash of the MRN after extraction is completed. 
If the MRN is specified as a field to be masked, in addition to masking the MRN in the Patient resource, there is an additional masking step after extraction is finished. All references to the MRN as an ID will be replaced by a hashed version of the MRN. Right now, the only places I found the MRN being used as an ID are in the `id` and `fullUrl` fields of the Patient resource and 'subject' and 'individual' objects in other resources.
- `patientUtils.js` now has a `maskMRN` function that takes a bundle as input, modifies the bundle to replace the …

Mask MRN when used as the ID of a Patient resource

---

src/extractors/CSVClinicalTrialInformationExtractor.js
src/templates/ResearchStudyTemplate.js
test/extractors/CSVClinicalTrialInformationExtractor.test.js
test/extractors/fixtures/csv-clinical-trial-information-bundle.json
test/templates/fixtures/research-study-resource.json
test/templates/researchStudy.test.js

clinicalSiteSystem can now be specified in the config file, similar to how clinicalSiteID is, except clinicalSiteSystem is optional
If a `clinicalSiteSystem` is added to the `constructorArgs` of `CSVClinicalTrialInformationExtractor` in the config file, that value will be used for the `system` field of the site object in the ResearchStudy resource. If no system is specified, the `system` field will be omitted in the output.
- `CSVClinicalTrialInformationExtractor.js` now takes an optional `clinicalSiteSystem` constructor argument and adds that to the formatted data for the Research Study
- `ResearchStudyTemplate.js` now takes an input for `clinicalSiteSystem` instead of just using an example.com value
- `CSVClinicalTrialInformationExtractor.test.js` and `researchStudy.test.js` have been …

Support specifying clinicalSiteSystem in configuration file

---

src/extractors/FHIRAdverseEventExtractor.js
src/helpers/contextUtils.js
test/extractors/FHIRAdverseEventExtractor.test.js
test/helpers/contextUtils.test.js

This PR uses context to find any ResearchStudy ids to be included in the FHIR Adverse Event search.
The `FHIRAdverseEventExtractor` now looks in context for any `ResearchStudy` resources. If it finds research study resources, it includes the study ids from all research studies in the `this.study` list of studies to be used when searching for AdverseEvents. If no research study resources are found, the AdverseEvent extractor still proceeds trying to search for AdverseEvents, but does not add any studies beyond the ones that were set in the constructor.
It also adds a new context util function for ResearchStudy resources.
This includes the new context util function and associated test. It also updates the (string) list of studies that is added in `parametrizeArgsForFHIRModule` in the …

Use ResearchStudy id from context in AdverseEvent search

---

src/extractors/CSVPatientExtractor.js
src/helpers/patientUtils.js
src/helpers/schemas/csv.js
src/templates/PatientTemplate.js
test/helpers/patientUtils.test.js
test/templates/fixtures/patient-resource.json
test/templates/patient.test.js

This PR makes it so that `familyName`, `givenName`, and `gender` are not required fields in CSVs. Because they are still required in the [mCODE Cancer Patient profile](http://hl7.org/fhir/us/mcode/StructureDefinition-mcode-cancer-patient.html), they are marked with `dataAbsentReason` extensions with a code `'unknown'`.
If `familyName`, `givenName`, or `gender` is not provided in the patient information CSV, no errors/warnings are logged and no data extracted. Further, if they are missing, the template will add a `dataAbsentReason` for `name` and `gender` in the patient resource because they have a `1..*` cardinality in mCODE. I thought about adding a warning or debug message to say those fields are recommended, but decided against it. If anyone likes the idea of that message, I can …

Loosen required fields for Patient CSV and mark missing required fields

---

src/client/BaseClient.js
src/helpers/fhirUtils.js
test/client/BaseClient.test.js
test/helpers/fhirUtils.test.js
test/helpers/fixtures/invalid-resource.json
test/helpers/fixtures/valid-resource.json

Adds the `invalidResourcesFromBundle` function to be used by the baseClient and other utilities that desire resource-level information on invalid bundles. Updates the baseClient to use this new function. Adds some basic tests for this fn and for the general isValidFhir function. Updates all FHIR-validation related `logger.error` messages to `logger.warn`, since the clients shouldn't fail on account of invalid FHIR.
To test this, an easy change to templates that renders the resulting FHIR invalid is to fix the gender value in PatientTemplate to an unknown enum value – `gender: invalid-gender` would work, for example. This should render all patient resources invalid and you should see as much when you run the baseclient in the form of a warning.

Added fn to find all invalid resources in a bundle

---

src/modules/CSVModule.js
test/modules/CSVModule.test.js
test/modules/fixtures/example-csv-bom.csv

This PR enables the CSV Module to read csvs with invisible Byte Order Marks at the beginning of a file.
The extractor now runs as expected when csvs containing a client's data include Byte Order Marks at the beginning of the file.
1. The `parse` function that's run in the CSVModule's contractor now has the `bom` flag set to true, causing any BOMs at the beginning of the csv to be ignored.
2. A new `example-csv-bom.csv` file has been added as a test fixture. It's identical to the preexisting `example-csv.csv` file, except it include a BOM at the beginning of the file.
3. A test case verifying that the CSV module ignores BOMs has been added to `CSVModule.test.js`
Commit `3dd1055` adds both an example csv with a BOM as well as a unit test that attempts to parse this CSV. The `bom` flag has …

CSV Module now ignores BOMs

---

README.md
package.json

You can now call `npm start -- [options]` to start the client instead of `node src/cli/cli.js [options]`
There is now a script in `package.json` called "start" that acts as a simpler way of calling the program from the command line. It is important to note that npm requires you to put "--" between your script name and command line arguments. If the double hyphen is left out, the arguments will be interpreted as npm flags, for example -d and -f will be interpreted as npm's debug and force flags, not our debug and from date flags.
- `package.json` now has a start script, which runs the client
- The README has been updated to include the new way of running the client
Make sure that you are able to use the client as usual when calling via the start script

Adding npm start script

---

docs/adverse-event.csv
docs/observation.csv
docs/procedure.csv
test/sample-client-data/condition-information.csv
test/sample-client-data/observation-information.csv
test/sample-client-data/procedure-information.csv
test/sample-client-data/staging-information.csv

This PR changes some of the example CSVs in the `docs` and `sample-client-data` directory to have values more representative of what the CSVModule is expecting. 
No new behavior.
* Unique sample Ids have been added to the condition, procedure, and observation CSVs within `test/sample-client-data`, and also to the adverse event, procedure, and observation CSVs within the `docs` folder. 
Ensure that I'm not missing anything that could potentially mislead users as they're creating their own CSVs. The only thing I saw that I thought required changing were some of the `id` fields not being unique when they should be in the context of FHIR, but I could be missing something.

Unique IDs added to several CSVs

---

README.md

Added section to README informing users that byte order markers are handled for UTF-8 and UTF-16 but may cause issues in other encodings and how they can check for BOMs in their CSVs
Read the new section of the README and make sure it is all correct and that I didn't leave anything out

Adding troubleshooting guide for BOMs

---

README.md

I noticed this when I was making the demo electron app to construct and call an extractor. This is out of date since the args are objects now

update docs to have correct construction of extractor

---

src/cli/app.js

The patient IDs CSV is parsed in `app.js` rather than in `CSVModule.js` like the other CSVs and we forgot to add the BOM flag to that instance of the parse function being called
BOMs are now handled when parsing the Patient IDs CSV
The call to the CSV parse function in `app.js` now has the flag to properly handle BOMs
To test that this works, you can go and replace the `fs.readFileSync()` call on line 87 of `app.js` with the following `'\uFEFFmrn\n123\n456\n789\n1011'` (the same as the sample client data but with a BOM added at the start). The client should still run as expected.

Add BOM flag to Patient ID CSV parsing

---

README.md
src/extractors/BaseCSVExtractor.js
src/extractors/CSVPatientExtractor.js
src/modules/CSVModule.js
test/modules/CSVModule.test.js

Adds behavior to the CSVModule to support normalization of NULL/NIL values into empty-string values. Additionally, CSVExtractors can now specify unalterableColumns in order to leave certain types of data immune from this normalization. 
- CSVModule now preprocesses CSV data in order to replace any values where `value.toLowerCase() === 'null' ||  value.toLowerCase() === 'nil'` with empty string `''`.
- CSVPatientExtractor now defines two unalterableColumns, familyName and givenName.
- BaseCSVExtractor now accepts `unalterableColumns` as a constructor argument and stores that value in local state.
- Adds tests of this new normalization functionality
- Ensure current tests pass.
- Try adding a NULL value to a CSV and see if it is appropriately replaced with an empty string (one option: …

Null is empty csv

---

src/cli/app.js
src/cli/cli.js

Delegates fatal error handling to the cli, rather than the `mcodeApp`.
When a fatal error is encountered in the `mcodeApp`, the running process is now closed from the cli rather than from within  the app. The cli also handles any logging that will result from that error.
1. Within `cli.js`, a new `runApp()` function is introduced. This function calls the `mcodeApp()` function from within a `try` block. If an error is encountered, this function will log the error and exit the node process. The `runApp()` function was necessary due to `mcodeApp()` being an asynchronous function, as calling an `async` function within a `try..catch` block can only be done from within an `async` function.
2. Within `app.js`, all fatal error handling within `mcodeApp()` has been removed. Errors are now thrown …

process.exit moved to cli.js

---

src/cli/app.js

Previously, the check for the default log file used a strict equality looking for the value `/logs/run-logs.json`, but now the paths compared will be resolved to allow for different but functionally equivalent paths like `./logs/run-logs.json` or `../mcode-extraction-framwork/logs/run-logs.json`, etc.
The `checkLogFile()` function in `app.js` now uses resolved paths to check for the default log file.
`checkLogFile()` in `app.js` updated with the change described above
To test this, starting with no default log file, the following commands should produce the same logs folder and file in the default location:
- `npm start -- -e -f 01-01-2019 -t 01-01-2021 -r ../mcode-extraction-framework/logs/run-logs.json`
- `npm start -- -e -f 01-01-2019 -t 01-01-2021`

Improve checking for default log file

---

src/cli/app.js
src/cli/cli.js

The function mcodeApp in src/cli/app.js was modified to return the extractedData object instead of writing the results to a file. src/cli/cli.js was modified to write the results of calling mocdeApp to a file.
cli.js writes the results of extraction to a file instead of app.js.
The code to write to a file was moved from app.js to cli.js and replaced with a return statement.
Use 'npm start' to run extraction.

Modified app.js to return object instead of writing to file; moved code to write to file to cli.js

---

src/helpers/schemas/config.schema.json

Add a basic schema for our csv config. **Note:** This schema is not complete. We just wanted a simple skeleton in here that we can expand on. This will allow us to parallelize some of the work of authoring the rest of the schema and using said schema in the app to report errors.
N/A
Added a schema file that will later be used for extractor config.
Head over to https://www.jsonschemavalidator.net/s/awUd23pG. This is an online playground that should have the schema from this PR and some sample content in the web. Try removing the "extractors" property which I've marked as required, or try removing the "type" property from an entry in the extractors array, which I've also marked required.
Just make sure the schema makes sense, can be built on, and works with some simple test cases in the …

Add initial schema for one config property

---

src/client/MCODEClient.js
src/helpers/dependencyUtils.js
test/cli/mcodeExtraction.test.js
test/helpers/dependencyUtils.test.js

Adds new `sortExtractors()` function called within `MCODEClient` which sorts extractors based on a predefined order (defined in `MCODEClient.js`) and will throw an error detailing any missing dependencies. Since there was some uncertainty over which method of implementing extractor dependencies was best, I would appreciate people's further thoughts after seeing this method in action and I wouldn't be against going back and trying another method if people think this isn't quite what we wanted.
Also, This new functionality makes a previous test fail (in `mcodeExtraction.test.js`). I didn't want to just remove it because I feel like we could modify the test to work a different way, I just wasn't sure how, so I would appreciate some help with that
If extractors are put out of order in the …

Adding implementation of extractor dependencies

---

src/application/app.js

Originally, the mcodeApp function in src/application/app.js only changed the logger level if debug was true, and didn't change it back to 'info' if debug was false. Since the UI can run extraction multiple times in a row, this caused a bug.
The mcodeApp function now changes the logger level back to 'info' if the debug flag is false.
The if statement on line 42 of src/application/app.js was changed to a ternary operator.
In the root package.json file of code-extraction-ui, set the location of mcode-extraction-framework to "file:local_file_path_to_framework". Run npm install, then npm start. Click on "Extract New", check "Log output debugging information", and then click "Submit". Either look at the terminal to see the logs or, if on the logger-display branch, click on "Log File" in the …

Debug flag bug

---

src/helpers/schemas/config.schema.json

Fill out the rest of the JSON schema for CSV config
N/A
Add all properties and some required ones to JSON Schema
[here](https://www.jsonschemavalidator.net/s/NFT5L56B) is a URL with the updated JSON schema loaded into the validator.
Play around with this, paste your config in, delete some properties, invalid data type stuff, etc.
A visual inspection of the schema is also a good idea, it's not too dense

Update csv config schema to include all properties

---

src/application/app.js
src/helpers/configValidator.js
src/helpers/schemas/config.schema.json
test/application/app.test.js
test/helpers/configValidator.test.js

The config  file is now checked for errors by validating it against the new config schema
When there are one or more errors in the config file, the client will fail and tell the user what is wrong with their config file
- `configValidator.js` contains the new `validateConfig()` function that performs validation
- `checkInputAndConfig()` in `app.js` now calls the new `validateConfig()` function instead of manually checking for `patientIdsCsvPath`
- Adjusted tests in `app.test.js` to work with the new validator
- Added new tests for the config validator in `configValidator.test.js`
- Ensure that when the config has no errors, the client still runs as expected
- Mess up the config file in more than one way (remove a required field, use a wrong type, use a wrong format) and make sure the …

Adding config file validator

---

README.md
src/client/BaseClient.js
src/helpers/fhirUtils.js
test/client/BaseClient.test.js
test/helpers/fhirUtils.test.js

This pull requests adds more detailed log information when a resource within the extracted bundle fails validation.
It introduces use of the `compile` function in AJV to generate a validator object that comes with `errors` we can filter and display in a more detailed manner.
We also now use the `subSchema` motif to pul off refs to specific resources in the schema that we wish to validate from within the loop, allowing us to collect all the error messages present for that resource rather than short circuit after one.
New log messages to the console when a resource fails validation. E.g.:
```
15:20:21.41 [warn]:     Extracted bundle is not valid FHIR, the following resources failed validation: Patient-789 at .gender
```
```
15:20:21.41 [warn]:     Extracted bundle is not valid FHIR, the …
```

New validation logging

---

src/helpers/configValidator.js
src/helpers/schemas/config.schema.json

Adding a custom format to the config validator that checks if a string has the format of emails separated by commas, for example: `whoever@whatver.com,somone@wherever.com`. This new format is used to validate the `notificationInfo.to` field in the config
The config validator will now ensure that the `notificationInfo.to` field of the config is either an array of emails or a string of emails separated by commas
- Custom format, `comma-separated-emails`, added to `configValidator.js` which splits a string at any commas, strips excess whitespace and then validates the resulting strings against Ajv's email format regex
- `config.schema.json` updated to use `comma-separated-emails` for `notificationInfo.to`
Here are some variations to test:
- `test@example.com` a single email should still be …

Adding custom schema format for comma separated emails

---

src/helpers/configValidator.js
src/helpers/schemas/config.schema.json

`notificationInfo.from` now uses a custom format for emails with a name in front of them. This format considers anything that ends with a valid email to be valid, for example: `Example Name example@demo.com`
Config validator has a new custom format that splits the input on spaces and checks that the last element is a valid email.
- `configValidator.js` now has new custom format `email-with-name` described above
- `config.schema.json` updated to use new format for `notificationInfo.from`
Cases to test:
- `Any number of words followed by anEmail@test.com` should be valid
- `justAnEmail@test.com` should be valid
- `Words with no email` should not be valid
- `emailFirst@test.com then some words` should not be valid

Adding email with name custom schema format

---

src/client/BaseClient.js
src/helpers/csvParsingUtils.js
src/modules/CSVURLModule.js

This PR addresses STEAM-670: 'CSVURLModule should validate the the URL it receives is a valid URL'. Upon closer inspection, it doesn't look like we do the level of validation we expected in the CSVFileModule. Accordingly, all this task takes up is better logging in fillDataCache logic. 
When a URL is provided that cannot be used successfully in CSV extraction, error messages are logged to the console. Additionally, debug messages have been added throughout the `fillDataCache` routine. 
- Logs added throughout the `fillDataCache` function.
- With a URL-enabled csv extractor, run the tool with a valid URL and ensure that extraction works. 
- With a URL-enabled csv extractor, run the tool with an invalid URL and ensure that the error message logs as expected. 
Below is an example (courtesy …

Better logging in the CSVURLModule 

---

package-lock.json
package.json
src/helpers/patientUtils.js
src/templates/ResourceGenerator.js

Removes the shajs dependency and uses the Node-native Crypto library. 
Ideally none.
Replaces all instances of the sha library with the crypto library. 
Ensure all tests pass.

Replaced shajs with crypto

---

src/templates/CancerDiseaseStatusTemplate.js
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/templates/fixtures/disease-status-resource.json
test/templates/fixtures/minimal-disease-status-resource.json

CancerDiseaseStatus profile now uses a newly-created LOINC code, 97509-4 “Cancer Disease Progression”. In STU 1, the LOINC code chosen to represent this observation (88040-1, “Response to cancer treatment”) did not precisely match the meaning of this profile because cancer disease status is observable regardless of whether the patient is under treatment
Cancer Disease Status template now uses the new LOINC code from STU2
- `CancerDiseaseStatusTemplate.js` now uses the new LOINC code
- Relevant test fixtures updated to match the new code
- Ensure that all tests pass
- Run the client with CancerDiseaseStatus and see that the output now contains the new LOINC code: `97509-4`
- Check if there are any updates from STU2 for the CancerDiseaseStatusTemplate that I missed

Updating CancerDiseaseStatusTemplate to STU2

---

src/templates/StagingTemplate.js
src/templates/TNMCategoryTemplate.js
test/extractors/fixtures/csv-staging-bundle.json
test/templates/fixtures/maximal-staging-resource.json
test/templates/fixtures/metastases-category-clinical-resource.json
test/templates/fixtures/metastases-category-pathologic-resource.json
test/templates/fixtures/minimal-staging-clinical-resource.json
test/templates/fixtures/minimal-staging-pathologic-resource.json
test/templates/fixtures/nodes-category-clinical-resource.json
test/templates/fixtures/nodes-category-pathologic-resource.json
test/templates/fixtures/tumor-category-clinical-resource.json
test/templates/fixtures/tumor-category-pathologic-resource.json

stagingTemplate: The profile TNMStageGroup is now renamed CancerStageGroup in order to support non-TNM staging systems such as Rai, Binet, and Revised International Staging System (R-ISS)
tnmCategoryTemplate: In STU2, the separate sets of profiles for TNM Clinical and TNM Pathologic staging were combined into a single set of profiles: [CancerStageGroup](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/StructureDefinition-mcode-cancer-stage-group.html), [TNMPrimaryTumorCategory](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/ValueSet-mcode-observation-codes-primary-tumor-vs.html), [TNMRegionalNodesCategory](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/StructureDefinition-mcode-tnm-regional-nodes-category.html), and …

Updating Staging and TNM Category Templates to STU2

---

README.md
src/helpers/patientUtils.js
test/extractors/fixtures/extended-patient-bundle.json
test/helpers/fixtures/masked-patient-bundle.json
test/helpers/patientUtils.test.js

Makes the following elements in the Patient resource maskable: `telecom`, `multipleBirth` (both `multipleBirthBoolean` and `multipleBirthInteger`), `photo`, `contact`, `generalPractitioner`, `managingOrganization`, and  `link`.
No changed behavior. The above elements are now supported as options within the `mask` array of the PatientExtractor config.
1. Support for new fields added to the `maskPatientData` function.
2. A new text fixture (`extended-patient-bundle.json`) was added to test masking, given that the newly supported fields are not supported by the CSVExtractors and will only ever occur in resources obtained via a FHIR search.
3. Updated readme to include the new masking fields.
1. Ensure that updated unit tests pass.
2. Ensure that the updated masking test fixture has elements …

New options for Patient masking

---

src/helpers/schemas/config.schema.json

Minor updates to our config file schema. Updates the `.notificationInfo.to` property so that: 
1. The AnyOf is changed to OneOf, which is more in line with what we want. For detailed explanations on the difference between these, see [here](https://json-schema.org/understanding-json-schema/reference/combining.html).
2. Each of the OneOf options have a title associated with them. This improves the result of rendering these options by React JSON Schema Form, which is used by the extraction-ui. A companion PR exists there and also needs to be reviewed.
Testing here should ensure that everything works as it previously did. Additionally, before merging these changes, we should review the extraction-ui and ensure that the visual changes look as desired.

updated schema; added titles to each possible to format

---

src/helpers/dateUtils.js
test/helpers/dateUtils.test.js

In addressing the root cause of broken E-MEF PerformanceStatus tests, we realized that the failing tests were due to the fact that our formatDateTime function was always interpretting timestamps according to the local timezone. This is according to the `moment()` constructor specification [found here](https://momentjs.com/docs/#/parsing/). Also found in the moment parsing documentation is guidance on the `moment.parseZone()` function, which will maintain the provided timezone in the parsing of a string and default to UTC if none is provided. 
This PR updates our use of moment in our formatDate functions to use this newly discovered method, leading to more robust testing fixtures on the E-MEF that don't depend on a testing machine running in the Eastern Time Zone

dateTimeStamp now localizes to UTC

---

README.md

Updates the README to reference that the extractor conforms to version 1.16.0 of the mCODE spec, and also updates the link to point to the [mCODE build IG](http://hl7.org/fhir/us/mcode/2021May/)
No new behavior.
No changes to code.
Just ensure that the README looks correct. The previous iteration linked to the mCODE IG's GitHub page (one that is no longer actively maintained). I thought it would be better to link to the IG page itself, but if folks disagree I can change the link to the [currently maintained GitHub page](https://github.com/HL7/fhir-mCODE-ig).

mCODE version update in Readme

---

src/helpers/appUtils.js
src/helpers/csvParsingUtils.js
src/modules/CSVFileModule.js
src/modules/CSVURLModule.js
test/modules/CSVFileModule.test.js
test/modules/fixtures/example-csv-empty-line.csv
test/modules/fixtures/example-csv-empty-values.csv

Supports ingestion of CSV's with either totally blank rows of data or rows with nothing by empty-values; in both cases those rows will be ignored. 
Now the CSVFileModule can ingest files with rows that meet the above criteria.
Some new tests
Make sure the tool still works.

Support CSVs with blank lines and empty values

---

README.md
config/csv.config.example.json
src/extractors/BaseCSVExtractor.js
src/extractors/CSVAdverseEventExtractor.js
src/extractors/CSVCTCAdverseEventExtractor.js
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/extractors/CSVCancerRelatedMedicationAdministrationExtractor.js
src/extractors/CSVCancerRelatedMedicationRequestExtractor.js
src/extractors/CSVClinicalTrialInformationExtractor.js
src/extractors/CSVConditionExtractor.js
src/extractors/CSVObservationExtractor.js
src/extractors/CSVPatientExtractor.js
src/extractors/CSVProcedureExtractor.js
src/extractors/CSVStagingExtractor.js
src/extractors/CSVTreatmentPlanChangeExtractor.js
src/extractors/index.js
src/helpers/schemas/config.schema.json
test/extractors/BaseCSVExtractor.test.js

CSVExtractors now support ingesting a `dataDirectory` & `fileName` argument pair, with which the extractor constructs an absolute path to a data file. This technique for specifying the location of a CSV file on disk is now the preferred method, in contrast with our previous `filePath` argument technique. Documentation, example config files, and schemas have been updated to reflect this. 
All CSVExtractors extending from the BaseCSVExtractor should now support the ingestion of `fileName` and `dataDirectory` arguments. The BaseCSVExtractor now considers a new case in the initial extractor construction to handle the consumption of these arguments. 
- Updated the README to reflect this argument pair as our preferred approach;
- Updated example config to use this approach by default;
- Updated …

CSVExtractors support dataDirectory & fileName arguments

---

src/application/app.js
src/helpers/appUtils.js
test/helpers/appUtils.test.js

Better error messaging in the event that someone expects the DataDirectory to inform the patientIdCsv read operation

Improving dataDirectory approach

---

README.md
config/csv.config.example.json
src/application/app.js
src/extractors/BaseCSVExtractor.js
src/extractors/CSVAdverseEventExtractor.js
src/extractors/CSVCTCAdverseEventExtractor.js
src/extractors/CSVCancerDiseaseStatusExtractor.js
src/extractors/CSVCancerRelatedMedicationAdministrationExtractor.js
src/extractors/CSVCancerRelatedMedicationRequestExtractor.js
src/extractors/CSVClinicalTrialInformationExtractor.js
src/extractors/CSVConditionExtractor.js
src/extractors/CSVObservationExtractor.js
src/extractors/CSVPatientExtractor.js
src/extractors/CSVProcedureExtractor.js
src/extractors/CSVStagingExtractor.js
src/extractors/CSVTreatmentPlanChangeExtractor.js
src/helpers/appUtils.js
src/helpers/schemas/config.schema.json
src/modules/CSVFileModule.js
src/modules/CSVURLModule.js

Adds support for a `csvParse` property within `commonExtractorArgs` of the config. Values included in the `options` property of this `csvParse` object will be passed to the `csv-parse` module as Extractors are initialized. Default options such as BOM removal and empty line skipping are still kept, but users can now override them (which is not recommended) or include their own in the event that they encounter errors while running the extractor. 
Properties included in the `commonExtractorArgs.csvParse.options` section of the config are passed to the `csv-parse` module to be used as the MEF reads CSV files. 
1. The `BaseCSVExtractor` (and each child Extractor class) now takes a `csvParse` argument in its constructor. The `BaseCSVExtractor` pulls the `options` property from this argument and …

Passthrough csv-parse options supported in the config

---

src/extractors/FHIRAdverseEventExtractor.js
src/helpers/contextUtils.js
src/index.js

Adds two new utility functions, `getAdverseEventsFromContext` and `getAdverseEventEntriesFromContext`.
1. New additions to `contextUtils` make it possible to fetch AdverseEvent resources in the context bundle.
2. The `FHIRAdverseEventExtractor` will now only throw an error if a `study` is not included in its contructorArgs. Previously, an error would be thrown whenever there were no `ResearchStudy` resources found in context, even though it's not exactly necessary if a `study` is included.
1. Two utility functions added to `contextUtils.js`.
2. Any errors thrown by `getResearchStudiesFromContext` are now logged as debug messages in `FHIRAdverseEventExtractor.js`, which a custom error being thrown by that Extractor if the `study` contructorArg isn't included either.
Testing guidance will …

Adverse Event context additions

---

src/extractors/CSVCancerDiseaseStatusExtractor.js
src/helpers/lookups/diseaseStatusLookup.js
test/extractors/fixtures/csv-cancer-disease-status-bundle.json
test/extractors/fixtures/csv-cancer-disease-status-module-response.json
test/helpers/diseaseStatusUtils.test.js

Updates our Cancer Disease Status code lookups to include 2 new codes added in the [STU2 Condition Status Trend Value Set](https://hl7.org/fhir/us/mcode/ValueSet-mcode-condition-status-trend-vs.html).
The extractor now supports displayText mappings for the two new requested codes in the aforementioned VS. 
1. New codes added to the CDS lookup file. 
2. Code System check added to the CDSExtractor to ensure the proper system is used for the two additional codes. 
3. CDSExtractor test fixtures updated to test the new changes.   
1. Ensure unit tests pass. 
2. Run the extractor with the two new codes (`USCRS-352236` or `USCRS-352237`) in the `diseaseStatusCode` column of the `cancer-disease-status-information` csv and the `diseaseStatusText` column blank. The resulting JSON should include the …

CDS 2022 Value Set Updates

---

src/helpers/csvParsingUtils.js
src/helpers/csvValidator.js
src/modules/CSVFileModule.js
src/modules/CSVURLModule.js
test/helpers/csvValidator.test.js

This PR modifies the CSV validator function to allow CSVs with the proper header row, but no data to be considered valid. This PR also adds trimming to CSV parsing so excess whitespace in the CSV should be removed on parsing
When a CSV with no data is parsed, the parser returns an empty array, which meant the headers were not passed into the validator and so it would fail. This PR stores the headers separately to be passed into the validator so that even CSVs with no data will be properly validated.
Additionally, the `trim: true` option was added to the default options of the csv parse function, which should allow CSVs with extra whitespace to still work properly (`mrn         ,    familyName...` for example)
- New `getCSVHeader()` function added to `csvParsingUtils.js`, which returns an …

Allowing CSVs with no rows + adding trimming to CSV parsing

---

src/extractors/CSVConditionExtractor.js
src/templates/ConditionTemplate.js
test/templates/condition.test.js

This PR modifies the `CSVConditionExtractor` to accept multiple codes by separating them with a `|` (e.g. `1234|5678`). Adding extra codes will result in extra entries in the coding array of the resulting condition resource.
Multiple condition codes in the csv file, separated by a `|` should result in extra codes in the coding array of the output, all with the same system and display name. This should work for any number of additional codes, but adding `|` without a code (e.g. `123|`) should result in an error
- `CSVConditionExtractor.js` now splits codes into an array and maps them to all have the same system and display
- `ConditionTemplate.js` now takes an array of codes in `codingTemplate()` and maps those to an array in the output
- Tests updated to reflect changes
- Ensure that …

Modifying conditions to allow  multiple codes

---

src/extractors/CSVConditionExtractor.js

Trims whitespace and better handles empty values when using the `|` delimiter to include multiple condition codes
Whitespace is now trimmed off the split codes so inputs like `123 | 456`, etc, should no longer cause an error. Empty code values resulting from inputs like `|123` or `456|` should now print a warning to the output but still generate a condition resource with the one available condition (previously this would have caused an error and stopped the resource from being generated)
- Make sure extraction still works as expected and all tests still pass
- Test that the type of inputs described above work as described and don't cause any errors

Trimming whitespace and handling empty values for additional condition codes

---

src/extractors/CSVAdverseEventExtractor.js
src/extractors/CSVCTCAdverseEventExtractor.js
src/extractors/CSVCancerRelatedMedicationAdministrationExtractor.js
src/extractors/CSVCancerRelatedMedicationRequestExtractor.js
src/extractors/CSVObservationExtractor.js
src/extractors/CSVProcedureExtractor.js
src/extractors/CSVStagingExtractor.js
src/helpers/schemas/csv.js

Not every extractor had a CSV schema, so this PR adds schemas to those that did not. 
Missing CSV values would previously throw an error during extraction, now all our bases should be covered and we should be able to catch missing required fields in the validation stage and throw an error before extraction.
- `helper/schemas/csv.js` has new schemas for: `CSVStagingExtractor`, `CSVAdverseEventExtractor`, `CSVCTCAdverseEventExtractor`, `CSVCancerRelatedMedicationAdministrationExtractor`, `CSVCancerRelatedMedicationRequestExtractor`, `CSVObservationExtractor`, `CSVProcedureExtractor `
- The above listed extractors now add the proper schema during construction
- Make sure that the new schemas properly list all fields and mark the appropriate fields as required
- Make sure extraction still …

Adding CSV schemas to remaining CSV extractors

---

.github/CODEOWNERS
src/extractors/CSVCancerRelatedMedicationRequestExtractor.js
src/helpers/schemas/csv.js
src/templates/CancerRelatedMedicationRequestTemplate.js
test/extractors/CSVCancerRelatedMedicationRequestExtractor.test.js
test/sample-client-data/cancer-related-medication-request-information.csv
test/templates/fixtures/minimal-medication-request.json
test/templates/medicationRequest.test.js

I went through and checked each CSV schema to double check required fields. In the end the only erroneously required field is `authoredOn` in the `CSVCancerRelatedMedicationRequestExtractor`, so I made the necessary changes to make it optional.
As we discussed before there are a number of extractors with `effectiveDate` as a required field, which isn't strictly required by the IG, but we decided was good to have required. I did also consider looking into if we can set them to trigger a soft warning in the validation stage instead of making them totally required, let me know what you think is the best thing to do.
There are also a few fields that we don't require in the schema even though they are required in the IG, but in all of these cases we insert a default value or a data absent …

Double checking schemas and un-requiring unnecessary required fields

---

src/extractors/CSVClinicalTrialInformationExtractor.js
src/helpers/schemas/csv.js
src/templates/EncounterTemplate.js
src/templates/ResearchSubjectTemplate.js
src/templates/snippets/index.js
src/templates/snippets/period.js
test/extractors/CSVClinicalTrialInformationExtractor.test.js
test/extractors/fixtures/csv-clinical-trial-information-bundle.json
test/extractors/fixtures/csv-clinical-trial-information-module-response.json
test/sample-client-data/clinical-trial-information.csv
test/templates/fixtures/research-subject-resource.json
test/templates/researchSubject.test.js

This PR adds the period field to the `ResearchSubject` generated by the `CSVClinicalTrialInformationExtractor` in the form of new optional `startDate` and `endDate` fields in the CSV template. Adding either or both fields to the CSV should result in a `period` in the output.
Additionally, this PR fixes `period` in the `CSVEncounterExtractor`. Accidentally made it so period would only show up if both start and end were present, but start and end are optional for periods, so you don't actually need both. This should work correctly now with just start or end
- Run the extractor and see that `ResearchSubject` resources in the output now have proper `period` fields
- Ensure that tests still pass and extraction still works as expected otherwise

Adding Period to ResearchSubjects in CSVClinicalTrialInformationExtractor

---

src/client/MCODEClient.js
src/extractors/CSVAppointmentExtractor.js
src/extractors/index.js
src/helpers/schemas/csv.js
src/index.js
src/templates/AppointmentTemplate.js
src/templates/ResourceGenerator.js
test/extractors/CSVAppointmentExtractor.test.js
test/extractors/fixtures/csv-appointment-bundle.json
test/extractors/fixtures/csv-appointment-module-response.json
test/sample-client-data/appointment-information.csv
test/templates/appointment.test.js
test/templates/fixtures/maximal-appointment-resource.json
test/templates/fixtures/minimal-appointment-resource.json

Adds CSVAppointmentExtractor, based on the [FHIR Appointment profile](https://hl7.org/fhir/R4/appointment.html).
New template created in `AppointmentTemplate.js`, new extractor in `CSVAppointmentExtractor.js`, additional changes to `MCODEClient.js`, `schemas/csv.js`, `ResourceGenerator.js` and various index files to add the new extractor to the client, and necessary test files and test fixtures added.
Add the following to the config file to test with the appointment extractor:
```
{
"label": "appointment",
"type": "CSVAppointmentExtractor",
"constructorArgs": {
"filePath": "./test/sample-client-data/appointment-information.csv"
}
}
```

Adding CSV Appointment Extractor

---

src/extractors/CSVCancerRelatedMedicationRequestExtractor.js
src/helpers/schemas/csv.js
src/templates/CancerRelatedMedicationRequestTemplate.js
test/extractors/fixtures/csv-medication-request-bundle.json
test/extractors/fixtures/csv-medication-request-module-response.json
test/sample-client-data/cancer-related-medication-request-information.csv
test/templates/fixtures/maximal-medication-request.json
test/templates/medicationRequest.test.js

This PR adds necessary CSV fields to the Cancer Related Medication Request Extractor to support the parts of `dosageInstruction` we need, route, dose quantity, type and as needed code. Timing is not included in this PR as we still need to check how we want to implement that field.
Run the extractor with the `CSVCancerRelatedMedicationRequestExtractor` and ensure that extraction still runs as expected and the new fields are properly generated

Adding dose related fields to medication request extractor

---

.eslintrc.json
package-lock.json
src/extractors/BaseFHIRExtractor.js
src/extractors/FHIRAdverseEventExtractor.js
src/extractors/FHIRAllergyIntoleranceExtractor.js
src/extractors/FHIRConditionExtractor.js
src/extractors/FHIRDocumentReferenceExtractor.js
src/extractors/FHIREncounterExtractor.js
src/extractors/FHIRMedicationOrderExtractor.js
src/extractors/FHIRMedicationRequestExtractor.js
src/extractors/FHIRMedicationStatementExtractor.js
src/extractors/FHIRObservationExtractor.js
src/extractors/FHIRPatientExtractor.js
src/extractors/FHIRProcedureExtractor.js
src/helpers/patientUtils.js
src/helpers/schemas/config.schema.json
test/extractors/BaseFHIRExtractor.test.js
test/extractors/FHIRAllergyIntoleranceExtractor.test.js
test/extractors/FHIRConditionExtractor.test.js
test/extractors/FHIRMedicationRequestExtractor.test.js
test/extractors/FHIRObservationExtractor.test.js

This PR adds the ability to configure search parameters for the FHIR extractors via construction arguments in the configuration file.  This allows us to potentially target specific resources and reduce the need for filtering data post extraction.  It also allows us to potentially use _include search filters to request additional information from a fhir server 
and reduce the number of requests we would need to make. 
Configuring search parameters in the construction arguments for FHIR extractors 
The FHIR extractors have been updated, the BaseFHIRExtractor class now accepts the new arguments and appends any search parameters to those returned with the patient id.   Removed all of the search params embedded in the extractors.  Updated the extractors to allow for the arguments and propagate …

Add search parameters

---

package-lock.json
package.json
src/client/MCODEClient.js
src/extractors/index.js
src/index.js

Exporting a list of extractors to be used in the base ICARE client. This should make it easier to keep the different clients in line when we add new extractors.

Exporting extractor list for use in other clients
